// export const BASE_URL = 'http://43.204.45.2:5002/api/v1'; //dev

export const BASE_URL = 'http://43.204.45.2:5000/api/v1'; //QA
// export const BASE_URL = 'http://43.204.45.2:5001/api/v1'; //prod

export const LOGIN_URL = BASE_URL + '/login';
export const REGISTER_URL = BASE_URL + '/signup';
export const GETDOCTORLIST_URL = BASE_URL + '/getdoctorlist';
export const SearchDoctorUrl = BASE_URL + '/searchDoctor';
export const GET_DOCTOR = BASE_URL + '/getdoctor';
export const GETAVAILABLITY_URL = BASE_URL + '/getavailability';
export const BOOKSLOT_URL = BASE_URL + '/bookSlot';
export const GETCLINICLIST_URL = BASE_URL + '/getcliniclist';
export const GETAPPOINTMENTS_URL = BASE_URL + '/getAppointments';
export const ADDADDRESS_URL = BASE_URL + '/addaddress';
export const GETADDRESS_URL = BASE_URL + '/getaddress';
export const GETBOOKINGAVAILABILITY_URL = BASE_URL + '/getBookingAvailability';
export const UPDATESLOTSSTATUS_URL = BASE_URL + '/updateSlotsStatus';
export const GETSPECIALITY_URL = BASE_URL + '/getSpeciality';
export const GETLOCATION_URL = BASE_URL + '/getLocation';
export const CUSTOMER_URL = BASE_URL + '/customer';
export const DOCUMENT = BASE_URL + '/document';
export const getAvailableDates_Url = BASE_URL + '/getAvailableDates';
export const createPayment_Url = BASE_URL + '/createPayment';
export const checkMobile_Url = BASE_URL + '/customer/checkMobile/';
export const sendOTP_Url = BASE_URL + '/sendOTP/';
export const reSendOTP_Url = BASE_URL + '/resendOTP/';
export const verifyOTP_Url = BASE_URL + '/verifyOTP/';
export const customerSignUp_URL = BASE_URL + '/customer';
export const sku_URL = BASE_URL + '/sku';
export const checkCode_URL = BASE_URL + '/checkCode';
export const reverseSearchCity_URL = BASE_URL + '/customerSearchCity';
