export const AppPages = {
  AuthHome: 'AuthHome',
  HomeStack: 'HomeStack',
  Home: 'Home',
  Search: 'Search',
  BookApointment: 'BookApointment',
  Doctorlist: 'Doctorlist',
  DoctorlistSpecialitywise: 'DoctorlistSpecialitywise',
  AppointmentStack: 'AppointmentStack',
  Appointment: 'Appointment',
  Payment: 'Payment',
  ProfileStack: 'ProfileStack',
  Profile: 'Profile',
  Offer: 'Offer',
  Contact: 'Contact',
  BookingConfirmation: 'BookingConfirmation',
};
